# Generated by Django 5.1.4 on 2024-12-10 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="is_admin",
            new_name="is_staff",
        ),
    ]
