# Generated by Django 5.1.4 on 2024-12-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="date",
            field=models.DateField(default="2021-11-11"),
            preserve_default=False,
        ),
    ]
