# Generated by Django 5.1.4 on 2024-12-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_alter_booking_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="purpose",
            field=models.CharField(default="none"),
            preserve_default=False,
        ),
    ]
